# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from fdilink_ahrs/original_imu.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class original_imu(genpy.Message):
  _md5sum = "31a1f3dfbaee0ca05acbe4ee8ad9dfc7"
  _type = "fdilink_ahrs/original_imu"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 gyroscope_x
float32 gyroscope_y
float32 gyroscope_z
float32 accelerometer_x
float32 accelerometer_y
float32 accelerometer_z"""
  __slots__ = ['gyroscope_x','gyroscope_y','gyroscope_z','accelerometer_x','accelerometer_y','accelerometer_z']
  _slot_types = ['float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       gyroscope_x,gyroscope_y,gyroscope_z,accelerometer_x,accelerometer_y,accelerometer_z

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(original_imu, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.gyroscope_x is None:
        self.gyroscope_x = 0.
      if self.gyroscope_y is None:
        self.gyroscope_y = 0.
      if self.gyroscope_z is None:
        self.gyroscope_z = 0.
      if self.accelerometer_x is None:
        self.accelerometer_x = 0.
      if self.accelerometer_y is None:
        self.accelerometer_y = 0.
      if self.accelerometer_z is None:
        self.accelerometer_z = 0.
    else:
      self.gyroscope_x = 0.
      self.gyroscope_y = 0.
      self.gyroscope_z = 0.
      self.accelerometer_x = 0.
      self.accelerometer_y = 0.
      self.accelerometer_z = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.gyroscope_x, _x.gyroscope_y, _x.gyroscope_z, _x.accelerometer_x, _x.accelerometer_y, _x.accelerometer_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.gyroscope_x, _x.gyroscope_y, _x.gyroscope_z, _x.accelerometer_x, _x.accelerometer_y, _x.accelerometer_z,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.gyroscope_x, _x.gyroscope_y, _x.gyroscope_z, _x.accelerometer_x, _x.accelerometer_y, _x.accelerometer_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.gyroscope_x, _x.gyroscope_y, _x.gyroscope_z, _x.accelerometer_x, _x.accelerometer_y, _x.accelerometer_z,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6f = None
def _get_struct_6f():
    global _struct_6f
    if _struct_6f is None:
        _struct_6f = struct.Struct("<6f")
    return _struct_6f
