// Generated by gencpp from file can_communication/CAN_srv.msg
// DO NOT EDIT!


#ifndef CAN_COMMUNICATION_MESSAGE_CAN_SRV_H
#define CAN_COMMUNICATION_MESSAGE_CAN_SRV_H

#include <ros/service_traits.h>


#include <can_communication/CAN_srvRequest.h>
#include <can_communication/CAN_srvResponse.h>


namespace can_communication
{

struct CAN_srv
{

typedef CAN_srvRequest Request;
typedef CAN_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CAN_srv
} // namespace can_communication


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::can_communication::CAN_srv > {
  static const char* value()
  {
    return "94cc95eb4903a2ce4eb831852c11ea30";
  }

  static const char* value(const ::can_communication::CAN_srv&) { return value(); }
};

template<>
struct DataType< ::can_communication::CAN_srv > {
  static const char* value()
  {
    return "can_communication/CAN_srv";
  }

  static const char* value(const ::can_communication::CAN_srv&) { return value(); }
};


// service_traits::MD5Sum< ::can_communication::CAN_srvRequest> should match
// service_traits::MD5Sum< ::can_communication::CAN_srv >
template<>
struct MD5Sum< ::can_communication::CAN_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::can_communication::CAN_srv >::value();
  }
  static const char* value(const ::can_communication::CAN_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::can_communication::CAN_srvRequest> should match
// service_traits::DataType< ::can_communication::CAN_srv >
template<>
struct DataType< ::can_communication::CAN_srvRequest>
{
  static const char* value()
  {
    return DataType< ::can_communication::CAN_srv >::value();
  }
  static const char* value(const ::can_communication::CAN_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::can_communication::CAN_srvResponse> should match
// service_traits::MD5Sum< ::can_communication::CAN_srv >
template<>
struct MD5Sum< ::can_communication::CAN_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::can_communication::CAN_srv >::value();
  }
  static const char* value(const ::can_communication::CAN_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::can_communication::CAN_srvResponse> should match
// service_traits::DataType< ::can_communication::CAN_srv >
template<>
struct DataType< ::can_communication::CAN_srvResponse>
{
  static const char* value()
  {
    return DataType< ::can_communication::CAN_srv >::value();
  }
  static const char* value(const ::can_communication::CAN_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAN_COMMUNICATION_MESSAGE_CAN_SRV_H
