// Generated by gencpp from file can_communication/CAN_srvRequest.msg
// DO NOT EDIT!


#ifndef CAN_COMMUNICATION_MESSAGE_CAN_SRVREQUEST_H
#define CAN_COMMUNICATION_MESSAGE_CAN_SRVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace can_communication
{
template <class ContainerAllocator>
struct CAN_srvRequest_
{
  typedef CAN_srvRequest_<ContainerAllocator> Type;

  CAN_srvRequest_()
    : Servo_Direction(0)  {
    }
  CAN_srvRequest_(const ContainerAllocator& _alloc)
    : Servo_Direction(0)  {
  (void)_alloc;
    }



   typedef int16_t _Servo_Direction_type;
  _Servo_Direction_type Servo_Direction;





  typedef boost::shared_ptr< ::can_communication::CAN_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::can_communication::CAN_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CAN_srvRequest_

typedef ::can_communication::CAN_srvRequest_<std::allocator<void> > CAN_srvRequest;

typedef boost::shared_ptr< ::can_communication::CAN_srvRequest > CAN_srvRequestPtr;
typedef boost::shared_ptr< ::can_communication::CAN_srvRequest const> CAN_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::can_communication::CAN_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::can_communication::CAN_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::can_communication::CAN_srvRequest_<ContainerAllocator1> & lhs, const ::can_communication::CAN_srvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.Servo_Direction == rhs.Servo_Direction;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::can_communication::CAN_srvRequest_<ContainerAllocator1> & lhs, const ::can_communication::CAN_srvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace can_communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::can_communication::CAN_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::can_communication::CAN_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::can_communication::CAN_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::can_communication::CAN_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can_communication::CAN_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can_communication::CAN_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::can_communication::CAN_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f2bcbe06881b4d460fdf3386210322b";
  }

  static const char* value(const ::can_communication::CAN_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f2bcbe06881b4d4ULL;
  static const uint64_t static_value2 = 0x60fdf3386210322bULL;
};

template<class ContainerAllocator>
struct DataType< ::can_communication::CAN_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "can_communication/CAN_srvRequest";
  }

  static const char* value(const ::can_communication::CAN_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::can_communication::CAN_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 Servo_Direction\n"
;
  }

  static const char* value(const ::can_communication::CAN_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::can_communication::CAN_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Servo_Direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CAN_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::can_communication::CAN_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::can_communication::CAN_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "Servo_Direction: ";
    Printer<int16_t>::stream(s, indent + "  ", v.Servo_Direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAN_COMMUNICATION_MESSAGE_CAN_SRVREQUEST_H
