// Generated by gencpp from file can_communication/Odrive_srvRequest.msg
// DO NOT EDIT!


#ifndef CAN_COMMUNICATION_MESSAGE_ODRIVE_SRVREQUEST_H
#define CAN_COMMUNICATION_MESSAGE_ODRIVE_SRVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace can_communication
{
template <class ContainerAllocator>
struct Odrive_srvRequest_
{
  typedef Odrive_srvRequest_<ContainerAllocator> Type;

  Odrive_srvRequest_()
    : Command(0)
    , Motor_pos(0.0)
    , Motor_vel(0.0)
    , Motor_tor(0.0)  {
    }
  Odrive_srvRequest_(const ContainerAllocator& _alloc)
    : Command(0)
    , Motor_pos(0.0)
    , Motor_vel(0.0)
    , Motor_tor(0.0)  {
  (void)_alloc;
    }



   typedef int16_t _Command_type;
  _Command_type Command;

   typedef float _Motor_pos_type;
  _Motor_pos_type Motor_pos;

   typedef float _Motor_vel_type;
  _Motor_vel_type Motor_vel;

   typedef float _Motor_tor_type;
  _Motor_tor_type Motor_tor;





  typedef boost::shared_ptr< ::can_communication::Odrive_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::can_communication::Odrive_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Odrive_srvRequest_

typedef ::can_communication::Odrive_srvRequest_<std::allocator<void> > Odrive_srvRequest;

typedef boost::shared_ptr< ::can_communication::Odrive_srvRequest > Odrive_srvRequestPtr;
typedef boost::shared_ptr< ::can_communication::Odrive_srvRequest const> Odrive_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::can_communication::Odrive_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::can_communication::Odrive_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::can_communication::Odrive_srvRequest_<ContainerAllocator1> & lhs, const ::can_communication::Odrive_srvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.Command == rhs.Command &&
    lhs.Motor_pos == rhs.Motor_pos &&
    lhs.Motor_vel == rhs.Motor_vel &&
    lhs.Motor_tor == rhs.Motor_tor;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::can_communication::Odrive_srvRequest_<ContainerAllocator1> & lhs, const ::can_communication::Odrive_srvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace can_communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::can_communication::Odrive_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::can_communication::Odrive_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::can_communication::Odrive_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::can_communication::Odrive_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can_communication::Odrive_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can_communication::Odrive_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::can_communication::Odrive_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "98395cca35dadc8c3b5dfe0ec65058cb";
  }

  static const char* value(const ::can_communication::Odrive_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x98395cca35dadc8cULL;
  static const uint64_t static_value2 = 0x3b5dfe0ec65058cbULL;
};

template<class ContainerAllocator>
struct DataType< ::can_communication::Odrive_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "can_communication/Odrive_srvRequest";
  }

  static const char* value(const ::can_communication::Odrive_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::can_communication::Odrive_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16   Command\n"
"float32 Motor_pos\n"
"float32 Motor_vel\n"
"float32 Motor_tor\n"
;
  }

  static const char* value(const ::can_communication::Odrive_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::can_communication::Odrive_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Command);
      stream.next(m.Motor_pos);
      stream.next(m.Motor_vel);
      stream.next(m.Motor_tor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Odrive_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::can_communication::Odrive_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::can_communication::Odrive_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "Command: ";
    Printer<int16_t>::stream(s, indent + "  ", v.Command);
    s << indent << "Motor_pos: ";
    Printer<float>::stream(s, indent + "  ", v.Motor_pos);
    s << indent << "Motor_vel: ";
    Printer<float>::stream(s, indent + "  ", v.Motor_vel);
    s << indent << "Motor_tor: ";
    Printer<float>::stream(s, indent + "  ", v.Motor_tor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAN_COMMUNICATION_MESSAGE_ODRIVE_SRVREQUEST_H
