// Generated by gencpp from file can_communication/Odrive_srv.msg
// DO NOT EDIT!


#ifndef CAN_COMMUNICATION_MESSAGE_ODRIVE_SRV_H
#define CAN_COMMUNICATION_MESSAGE_ODRIVE_SRV_H

#include <ros/service_traits.h>


#include <can_communication/Odrive_srvRequest.h>
#include <can_communication/Odrive_srvResponse.h>


namespace can_communication
{

struct Odrive_srv
{

typedef Odrive_srvRequest Request;
typedef Odrive_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Odrive_srv
} // namespace can_communication


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::can_communication::Odrive_srv > {
  static const char* value()
  {
    return "e522f0b6d497b2dedc7ffe665b11fc10";
  }

  static const char* value(const ::can_communication::Odrive_srv&) { return value(); }
};

template<>
struct DataType< ::can_communication::Odrive_srv > {
  static const char* value()
  {
    return "can_communication/Odrive_srv";
  }

  static const char* value(const ::can_communication::Odrive_srv&) { return value(); }
};


// service_traits::MD5Sum< ::can_communication::Odrive_srvRequest> should match
// service_traits::MD5Sum< ::can_communication::Odrive_srv >
template<>
struct MD5Sum< ::can_communication::Odrive_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::can_communication::Odrive_srv >::value();
  }
  static const char* value(const ::can_communication::Odrive_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::can_communication::Odrive_srvRequest> should match
// service_traits::DataType< ::can_communication::Odrive_srv >
template<>
struct DataType< ::can_communication::Odrive_srvRequest>
{
  static const char* value()
  {
    return DataType< ::can_communication::Odrive_srv >::value();
  }
  static const char* value(const ::can_communication::Odrive_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::can_communication::Odrive_srvResponse> should match
// service_traits::MD5Sum< ::can_communication::Odrive_srv >
template<>
struct MD5Sum< ::can_communication::Odrive_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::can_communication::Odrive_srv >::value();
  }
  static const char* value(const ::can_communication::Odrive_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::can_communication::Odrive_srvResponse> should match
// service_traits::DataType< ::can_communication::Odrive_srv >
template<>
struct DataType< ::can_communication::Odrive_srvResponse>
{
  static const char* value()
  {
    return DataType< ::can_communication::Odrive_srv >::value();
  }
  static const char* value(const ::can_communication::Odrive_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAN_COMMUNICATION_MESSAGE_ODRIVE_SRV_H
