// Generated by gencpp from file can_communication/VESC_srv.msg
// DO NOT EDIT!


#ifndef CAN_COMMUNICATION_MESSAGE_VESC_SRV_H
#define CAN_COMMUNICATION_MESSAGE_VESC_SRV_H

#include <ros/service_traits.h>


#include <can_communication/VESC_srvRequest.h>
#include <can_communication/VESC_srvResponse.h>


namespace can_communication
{

struct VESC_srv
{

typedef VESC_srvRequest Request;
typedef VESC_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VESC_srv
} // namespace can_communication


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::can_communication::VESC_srv > {
  static const char* value()
  {
    return "97cac9bdb9cfc7ba3044e440153b1b6d";
  }

  static const char* value(const ::can_communication::VESC_srv&) { return value(); }
};

template<>
struct DataType< ::can_communication::VESC_srv > {
  static const char* value()
  {
    return "can_communication/VESC_srv";
  }

  static const char* value(const ::can_communication::VESC_srv&) { return value(); }
};


// service_traits::MD5Sum< ::can_communication::VESC_srvRequest> should match
// service_traits::MD5Sum< ::can_communication::VESC_srv >
template<>
struct MD5Sum< ::can_communication::VESC_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::can_communication::VESC_srv >::value();
  }
  static const char* value(const ::can_communication::VESC_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::can_communication::VESC_srvRequest> should match
// service_traits::DataType< ::can_communication::VESC_srv >
template<>
struct DataType< ::can_communication::VESC_srvRequest>
{
  static const char* value()
  {
    return DataType< ::can_communication::VESC_srv >::value();
  }
  static const char* value(const ::can_communication::VESC_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::can_communication::VESC_srvResponse> should match
// service_traits::MD5Sum< ::can_communication::VESC_srv >
template<>
struct MD5Sum< ::can_communication::VESC_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::can_communication::VESC_srv >::value();
  }
  static const char* value(const ::can_communication::VESC_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::can_communication::VESC_srvResponse> should match
// service_traits::DataType< ::can_communication::VESC_srv >
template<>
struct DataType< ::can_communication::VESC_srvResponse>
{
  static const char* value()
  {
    return DataType< ::can_communication::VESC_srv >::value();
  }
  static const char* value(const ::can_communication::VESC_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAN_COMMUNICATION_MESSAGE_VESC_SRV_H
