controller_list:
  - name: fake_bicycle_kdl_controller
    type: $(arg fake_execution_type)
    joints:
      - j1
      - j2
initial:  # Define initial robot poses per group
#  - group: bicycle_kdl
#    pose: home

  []